### ISSUE TITLE
Font files ending up in the wrong place.

### ISSUE THREAD

**Issue by martinholmin** [middleman/middleman-sprockets#94]
Hi! I tried updating a project to MM4 using `middleman-sprockets (4.0.0.rc.1)`. The project uses the `materialize-sass` gem.

In my `config.rb` i have set the `fonts_dir` to `assets/fonts`. While running the preview server or middleman build I used to get the fonts in `assets/fonts/fontname/font-file.woff`

Here are some selected output from the `middleman build` going from v3 to v4 with a persisted build directory to clarify the issue. 

```
create  build/assets/roboto/Roboto-Light-6300f659.woff
create  build/assets/roboto/Roboto-Medium-d45f8492.woff
...
remove  build/assets/fonts/roboto/Roboto-Bold-47327df0.ttf
remove  build/assets/fonts/roboto/Roboto-Bold-933b866d.woff2
```
Any help appreciated

**Comment by stevenosloan** [comment]
This is expected behavior in middleman-sprockets 4.0.x, and something that should/will be explained the in upgrading guide (that's coming). With 4.0.x we've stopped trying to detect file type and rewrite paths based on that -- everything will get dumped into `imported_asset_path` option, which defaults to `assets`.

Are you having any issues with link helpers pointing to the wrong locations though?

**Comment by martinholmin** [comment]
Thanks for the reply! No, it's not causing any real issues. Link helpers seems to be working fine!
